export var state = {
  tree: null,
  changeLog: [],
  currentNodeId: null,
  history: [],
  currentMode: 'node',
  currentPayload: null,
  comments: {},
  currentResult: null,
  loadedFileName: 'tree.json',
  editorMode: 'form',
  editorDraft: null,
  createDraft: null,
  createMode: null,
  lastTreeSnapshot: null,
  sessionLinks: {},
  sessionId: '',
  supersedesSessionId: '',
  previousSessionIds: [],
  iconPickerScope: null,
  editorSurfaceMode: 'edit',
  editorDraftBaseline: null,
  createDraftBaseline: null
};
